import { Html, Head, Main, NextScript } from "next/document";
import Script from "next/script";
export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/static/icon.png" />
      </Head>
      {/* <Script
        src="https://cdn.onesignal.com/sdks/OneSignalSDK.js"
        strategy="lazyOnload"
      /> */}
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
